"""modify classified table

Revision ID: 39aeb844609d
Revises: 606a3a674b3d
Create Date: 2026-10-03 15:33:05.896180

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = '39aeb844609d'
down_revision: Union[str, None] = '606a3a674b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fb_listings_classified', sa.Column('is_relevant_listing', sa.Boolean(), nullable=True), schema='facebook')
    op.drop_column('fb_listings_classified', 'is_store_seller', schema='facebook')
    op.drop_column('fb_listings_classified', 'is_genuine_listing', schema='facebook')
    op.drop_column('fb_listings_classified', 'is_unlocked', schema='facebook')
    op.drop_column('fb_listings_classified', 'is_scam_risk', schema='facebook')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fb_listings_classified', sa.Column('is_scam_risk', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='facebook')
    op.add_column('fb_listings_classified', sa.Column('is_unlocked', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='facebook')
    op.add_column('fb_listings_classified', sa.Column('is_genuine_listing', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='facebook')
    op.add_column('fb_listings_classified', sa.Column('is_store_seller', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='facebook')
    op.drop_column('fb_listings_classified', 'is_relevant_listing', schema='facebook')
    # ### end Alembic commands ###
