"""add notification tables

Revision ID: 758a87b2ab9d
Revises: 39aeb844609d
Create Date: 2026-10-08 21:30:22.443715

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '758a87b2ab9d'
down_revision: Union[str, None] = '39aeb844609d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_listing_ids', postgresql.ARRAY(sa.BigInteger()), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='facebook'
    )
    op.create_index('idx_notification_created_at', 'notification_log', ['created_at'], unique=False, schema='facebook')
    op.create_index('idx_notification_message_id', 'notification_log', ['message_id'], unique=False, schema='facebook')
    op.create_table('deal_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_listing_id', sa.BigInteger(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_notification_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['email_notification_id'], ['facebook.notification_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_listing_id'),
    schema='facebook'
    )
    op.create_index('idx_deal_alerts_email_notification_id', 'deal_alerts', ['email_notification_id'], unique=False, schema='facebook')
    op.create_index('idx_deal_alerts_evaluated_at', 'deal_alerts', ['evaluated_at'], unique=False, schema='facebook')
    op.create_index('idx_deal_alerts_unsent', 'deal_alerts', ['raw_listing_id'], unique=False, schema='facebook', postgresql_where=sa.text('email_sent_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_deal_alerts_unsent', table_name='deal_alerts', schema='facebook', postgresql_where=sa.text('email_sent_at IS NULL'))
    op.drop_index('idx_deal_alerts_evaluated_at', table_name='deal_alerts', schema='facebook')
    op.drop_index('idx_deal_alerts_email_notification_id', table_name='deal_alerts', schema='facebook')
    op.drop_table('deal_alerts', schema='facebook')
    op.drop_index('idx_notification_message_id', table_name='notification_log', schema='facebook')
    op.drop_index('idx_notification_created_at', table_name='notification_log', schema='facebook')
    op.drop_table('notification_log', schema='facebook')
    # ### end Alembic commands ###
