"""update deal alerts table

Revision ID: b680bfbae539
Revises: 758a87b2ab9d
Create Date: 2026-10-09 17:23:45.476589

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b680bfbae539'
down_revision: Union[str, None] = '758a87b2ab9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_alerts', sa.Column('fb_listing_id', sa.Text(), nullable=False), schema='facebook')
    op.add_column('deal_alerts', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False), schema='facebook')
    op.drop_constraint(op.f('deal_alerts_raw_listing_id_key'), 'deal_alerts', schema='facebook', type_='unique')
    op.drop_index(op.f('idx_deal_alerts_unsent'), table_name='deal_alerts', schema='facebook', postgresql_where='(email_sent_at IS NULL)')
    op.create_index('idx_deal_alerts_unsent', 'deal_alerts', ['id'], unique=False, schema='facebook', postgresql_where=sa.text('email_sent_at IS NULL'))
    op.create_index('idx_deal_alerts_raw_listing_id', 'deal_alerts', ['raw_listing_id'], unique=False, schema='facebook')
    op.create_unique_constraint('uq_deal_alerts_listing_price', 'deal_alerts', ['fb_listing_id', 'price'], schema='facebook')
    op.add_column('notification_log', sa.Column('listing_count', sa.Integer(), nullable=False), schema='facebook')
    op.drop_column('notification_log', 'raw_listing_ids', schema='facebook')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_log', sa.Column('raw_listing_ids', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=False), schema='facebook')
    op.drop_column('notification_log', 'listing_count', schema='facebook')
    op.drop_constraint('uq_deal_alerts_listing_price', 'deal_alerts', schema='facebook', type_='unique')
    op.drop_index('idx_deal_alerts_raw_listing_id', table_name='deal_alerts', schema='facebook')
    op.drop_index('idx_deal_alerts_unsent', table_name='deal_alerts', schema='facebook', postgresql_where=sa.text('email_sent_at IS NULL'))
    op.create_index(op.f('idx_deal_alerts_unsent'), 'deal_alerts', ['raw_listing_id'], unique=False, schema='facebook', postgresql_where='(email_sent_at IS NULL)')
    op.create_unique_constraint(op.f('deal_alerts_raw_listing_id_key'), 'deal_alerts', ['raw_listing_id'], schema='facebook', postgresql_nulls_not_distinct=False)
    op.drop_column('deal_alerts', 'price', schema='facebook')
    op.drop_column('deal_alerts', 'fb_listing_id', schema='facebook')
    # ### end Alembic commands ###
