fb_marketplace:
  target: prod
  outputs:
    prod:
      type: athena
      region_name: "{{ env_var('DBT_REGION') }}"
      s3_staging_dir: "{{ env_var('DBT_S3_STAGING_DIR') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      work_group: "{{ env_var('DBT_WORKGROUP') }}"
      threads: 4
      aws_profile_name: null
